CREATE TABLE feedback_lms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  util VARCHAR(10) NULL,          
  mensagem TEXT NOT NULL,
  pagina VARCHAR(100) NULL,
  ip VARCHAR(45) NULL,
  user_agent VARCHAR(255) NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
